spring:
  application:
    name: news-hub
  profiles:
    include: SECRET-KEY
  datasource:
    url: ${mysql-url}
    username: ${mysql-username}
    password: ${mysql-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  jackson:
    property-naming-strategy: SNAKE_CASE
springdoc:
  swagger-ui:
    path: /swagger
server:
  servlet:
    session:
      tracking-modes: cookie
scheduler:
  use: false
  general-cron: 0 0 0/1 * * ?
  top-cron: 0 0 12 * * ?